#!/usr/bin/python -tt
# vim: fileencoding=utf8

import sys


from encryptmail.config import global_config, SYSTEMCONFIGFILE
from encryptmail.sendmail import sendmail


if __name__ == "__main__":
    global_config.update_yaml_file(SYSTEMCONFIGFILE)
    sys.exit(sendmail(global_config["mta"]["listen_address"]))
